### ISSUE TITLE
Make SnsPayload exported to use in Typescript

### ISSUE THREAD

**Issue by salientsysios** [devinstewart/sns-payload-validator#24]
Hey Devin,

Love your work on the validator. In fact, I started using the lib on my project.

Would you be able to make `SnsPayload` exported as well? My project is written in Typescript and I'd love to have that type available to use

Thank you

**Comment by devinstewart** [comment]
Sure thing.  Will get to it this week.  Was actually going to write up a contributing document stating, this now does everything I need, so feel free to open a issues or create PR's.

I will include exporting `SnsPayload` in that release as well.

**Comment by devinstewart** [comment]
@salientsysios -- I am going to pull this PR in, which will close this issue.  I will publish to `1.0.3` to NPM in a few hours, which will include this feature.

If there is something you still need, feel free to open another issue.

Thanks for your interest in this project -- Devin
