### ISSUE TITLE
Cloudflare Worker / "client-side" usage?

### ISSUE THREAD

**Issue by Manouchehri** [devinstewart/sns-payload-validator#51]
First of all, thanks for making this library!

I was interested in using it in a Cloudflare Worker, but realized it relies on Node.js' crypto module. Not sure how I could sanely add in support for Web Crypto. https://developers.cloudflare.com/workers/runtime-apis/web-crypto/#constructors

Might create a PR myself if I figure it out in a reasonable amount of time.

**Comment by devinstewart** [comment]
Yes, it does use Node's `crypto`.  But feel free to give it a shot.  If you feel like you are 80% there, let me know and perhaps I can help close the gap.

**Comment by devinstewart** [comment]
@Manouchehri - Thought on this a bit.  Where I'm confused is that SNS aways does a `POST`.  How are you setup that you can handle a `POST` _client side_?

Perhaps this is a Cloudflare thing.  I'm used to just good old React / Angular / Solid routing which only handles GET's unless you are doing SSR.

Let me know if you can provide more info, as my curiosity is now peaked. 😄

**Comment by Manouchehri** [comment]
Sorry, I put "client-side" in quotes, because Cloudflare Workers are still server-side. =P It's just that they use a pretty vanilla V8 runtime, so it's easier to think of compatibility as if it was running "client-side".

**Comment by devinstewart** [comment]
OK, cause my next thought was that it is using Node's `https` library.  Perhaps we might want to create a different library for Cloudfare, using the same principles but with the methods available in _Cloudfare Workers_. 

Feel free to keep working on a PR if you want.  I'm pretty stacked the next couple days, but I might set myself up with a Cloudfare account this weekend and see what's what.

**Comment by Manouchehri** [comment]
I ended up rewriting most of it, not sure if a PR really makes sense anymore.

https://gist.github.com/Manouchehri/5eac5fdf02b159e479e07c1c90f903a7

**Comment by devinstewart** [comment]
Well done.  Yeah, as I thought, this is probably a totally different module.  If you have what you need, glad I could give you the inspiration.  If you want to work together to create a new module so we can have test coverage, documentation, etc.. let me know.

**Comment by devinstewart** [comment]
Closing due to being out of scope of this module.  Will perhaps hit it up in the next couple weeks.

**Comment by devinstewart** [comment]
@Manouchehri  - **TL;DR** - If you still have a need, checkout https://github.com/devinstewart/sns-cloudflare-validator/

I had someone else hit me up about Cloudflare.  As you saw in your gist, the "key" is extracting the Public Key from the x509 Certificate.  I didn't want to include any of the huge modules that do that kind of stuff in a module I am maintaining, so I adapted only the needed  code from [node-forge](https://github.com/digitalbazaar/forge), and of course attributed them at the top of the file.

After that was the challenge of testing a Cloudflare Worker (ESM) that makes a fetch call that needs to be intercepted.

Feel free to check it out and give it for a spin.
